src/main/java/com/openthinks/webscheduler/model/TaskRunTimeData.java
package com.openthinks.webscheduler.model;

import java.io.IOException;
import java.io.Serializable;
import java.util.Optional;
import java.util.UUID;

import com.openthinks.webscheduler.help.StaticDict;
import com.openthinks.webscheduler.model.task.DefaultTaskRef;
import com.openthinks.webscheduler.model.task.ITaskRef;
import com.openthinks.webscheduler.model.task.ITaskTrigger;
import com.openthinks.webscheduler.model.task.TaskResult;
import com.openthinks.webscheduler.model.task.TaskState;
import com.openthinks.webscheduler.task.ITaskDefinition;

/**
 * Task runtime record data
 * @author dailey.yet@outlook.com
 *
 */
public class TaskRunTimeData implements Serializable, Updateable<TaskRunTimeData> {
	/**
	 * 
	 */
	private static final long serialVersionUID = -9156251287769007398L;

	private String taskId;
	private String taskName;
	private String taskType;
	private String groupName;

	private ITaskRef taskRef;
	private String taskRefContent;

	private volatile TaskState taskState;

	private TaskResult lastTaskResult;

	private ITaskTrigger taskTrigger;

	//user id
	private String createdBy = null;

	//shared for other guys or private
	private boolean shared = true;

	public TaskRunTimeData() {
	}

	public void makeDefault() {
		taskId = UUID.randomUUID().toString();
		taskName = "default_task";
		groupName = StaticDict.DEFAULT_TASK_GROUP_NAME;
		taskState = TaskState.UN_SCHEDULE;
		taskRef = new DefaultTaskRef();
		taskRefContent = "";
		lastTaskResult = new TaskResult(taskId);
		createdBy = null;
		shared = true;
	}

	public String getTaskId() {
		return taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	public String getTaskName() {
		return taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	/**
	 * Task definition class full name; like com.openthinks.webscheduler.task.support.EchoTask
	 * @return String
	 */
	public String getTaskType() {
		return taskType;
	}

	/**
	 * Task definition class simple name; like EchoTask
	 * @return String
	 */
	public String getTaskTypeShort() {
		try {
			return getTaskClass().getSimpleName();
		} catch (ClassNotFoundException e) {
			String[] names = getTaskType().split("\\.");
			return names[names.length - 1];
		}
	}

	public void setTaskType(String taskType) {
		this.taskType = taskType;
	}

	public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public ITaskRef getTaskRef() {
		return taskRef;
	}

	public void setTaskRef(ITaskRef taskRef) {
		this.taskRef = taskRef;
	}

	public TaskState getTaskState() {
		return taskState;
	}

	public void setTaskState(TaskState taskState) {
		this.taskState = taskState;
	}

	public String getTaskRefContent() {
		return taskRefContent;
	}

	public void setTaskRefContent(String taskRefContent) {
		this.taskRefContent = taskRefContent;
	}

	public TaskResult getLastTaskResult() {
		return lastTaskResult;
	}

	public void setLastTaskResult(TaskResult lastTaskResult) {
		this.lastTaskResult = lastTaskResult;
	}

	public ITaskTrigger getTaskTrigger() {
		return taskTrigger;
	}

	public void setTaskTrigger(ITaskTrigger taskTrigger) {
		this.taskTrigger = taskTrigger;
	}

	/**
	 * check current record is valid or not
	 * @return boolean
	 */
	public boolean isValid() {
		return taskState != null && taskState != TaskState.INVALID;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * when createdBy is empty, then whatever the value of shared, still take shared as true 
	 * @return this task runtime data is shared or private
	 */
	public boolean isShared() {
		return shared == true ? true : getCreatedBy() == null;
	}
	
	public boolean getRelShared(){
		return this.shared;
	}

	public void setShared(boolean shared) {
		this.shared = shared;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((taskId == null) ? 0 : taskId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TaskRunTimeData other = (TaskRunTimeData) obj;
		if (taskId == null) {
			if (other.taskId != null)
				return false;
		} else if (!taskId.equals(other.taskId))
			return false;
		return true;
	}

	/**
	 * get associated task class
	 * @return Class<T> 
	 * @throws ClassNotFoundException
	 */
	@SuppressWarnings("unchecked")
	public <T extends ITaskDefinition> Class<T> getTaskClass() throws ClassNotFoundException {

		return (Class<T>) Class.forName(getTaskType());
	}

	/**
	 * convert the task reference from text to {@link ITaskRef} 
	 * @see DefaultTaskRef
	 */
	public void preparedTaskRef() {
		if (!this.hasTaskRef()) {
			this.taskRef = new DefaultTaskRef();
		}
		try {
			this.taskRef.readString(getTaskRefContent());
		} catch (IOException e) {
			//ignore
		}
	}

	/**
	 * when {@link #getTaskRef()} return null, use the given @param taskRef
	 * @param taskRef ITaskRef
	 */
	public void preparedTaskRef(ITaskRef taskRef) {
		if (taskRef != null) {
			this.taskRef = taskRef;
		}
		if (!this.hasTaskRef()) {
			try {
				taskRef.readString(this.getTaskRefContent());
				setTaskRef(taskRef);
			} catch (IOException e) {
				//ignore
			}
		} else {
			this.preparedTaskRef();
		}
	}

	public boolean hasTaskRef() {
		return this.taskRef != null;
	}

	public Optional<String> getRefProp(String propertyName) {
		if (this.taskRef != null) {
			return this.taskRef.getProp(propertyName);
		}
		return Optional.empty();
	}

	@Override
	public String toString() {
		return "TaskRunTimeData [taskId=" + taskId + ", taskName=" + taskName + ", taskType=" + taskType
				+ ", groupName=" + groupName + ", taskRef=" + taskRef + ", taskRefContent=" + taskRefContent
				+ ", taskState=" + taskState + ", lastTaskResult=" + lastTaskResult + ", taskTrigger=" + taskTrigger
				+ ", createdBy=" + createdBy + ", shared=" + shared + "]";
	}

	//	/**
	//	 * update current task runtime record data by other
	//	 * @param taskMetaDataNew TaskRunTimeData New instance of task runtime record data
	//	 */
	//	@Override
	//	public void update(TaskRunTimeData taskMetaDataNew) {
	//		if (taskMetaDataNew.getTaskId() != null)
	//			this.setTaskId(taskMetaDataNew.getTaskId());
	//		if (taskMetaDataNew.getTaskName() != null)
	//			this.setTaskName(taskMetaDataNew.getTaskName());
	//		if (taskMetaDataNew.getTaskType() != null)
	//			this.setTaskType(taskMetaDataNew.getTaskType());
	//		if (taskMetaDataNew.getGroupName() != null)
	//			this.setGroupName(taskMetaDataNew.getGroupName());
	//		if (taskMetaDataNew.getTaskRef() != null)
	//			this.setTaskRef(taskMetaDataNew.getTaskRef());
	//		if (taskMetaDataNew.getTaskState() != null)
	//			this.setTaskState(taskMetaDataNew.getTaskState());
	//		if (taskMetaDataNew.getTaskRefContent() != null)
	//			this.setTaskRefContent(taskMetaDataNew.getTaskRefContent());
	//		if (taskMetaDataNew.getLastTaskResult() != null)
	//			this.setLastTaskResult(taskMetaDataNew.getLastTaskResult());
	//	}
}

src/main/java/com/openthinks/webscheduler/model/task/DefaultTaskRef.java
/**   
 *  Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
* @Title: DefaultTaskRef.java 
* @Package com.openthinks.webscheduler.model 
* @Description: TODO
* @author dailey.yet@outlook.com  
* @date Jul 13, 2016
* @version V1.0   
*/
package com.openthinks.webscheduler.model.task;

import java.io.IOException;
import java.io.InputStream;
import java.io.StringWriter;
import java.util.InvalidPropertiesFormatException;
import java.util.Properties;

import com.openthinks.libs.utilities.logger.ProcessLogger;
import com.openthinks.webscheduler.task.TaskRefDefinitionDescriber;

/**
 * Default implementation by extends {@link Properties}
 * @author dailey.yet@outlook.com
 *
 */
public class DefaultTaskRef extends Properties implements ITaskRef {

	private static final long serialVersionUID = 128536257786984503L;

	public static final DefaultTaskRef readXML(InputStream is) throws InvalidPropertiesFormatException, IOException {
		DefaultTaskRef instance = new DefaultTaskRef();
		instance.loadFromXML(is);
		return instance;
	}

	public static final DefaultTaskRef readProps(InputStream is) throws IOException {
		DefaultTaskRef instance = new DefaultTaskRef();
		instance.load(is);
		return instance;
	}

	public static final TaskRefDefinitionDescriber getTaskRefDescriber() {
		return new TaskRefDefinitionDescriber(DefaultTaskRef.class) {
			@SuppressWarnings("unchecked")
			@Override
			public <T extends ITaskRef> T createTaskRef() {
				return (T) new DefaultTaskRef();
			}
		};
	}

	public static final TaskRefDefinitionDescriber getTaskRefDescriber(String description) {
		return new TaskRefDefinitionDescriber(DefaultTaskRef.class, description) {
			@SuppressWarnings("unchecked")
			@Override
			public <T extends ITaskRef> T createTaskRef() {
				return (T) new DefaultTaskRef();
			}
		};
	}

	public String getContent() {
		StringWriter stringWriter = new StringWriter();
		try {
			this.store(stringWriter, "");
		} catch (IOException e) {
			ProcessLogger.warn(e);
		} finally {
			try {
				stringWriter.close();
			} catch (IOException e) {
				ProcessLogger.warn(e);
			}
		}
		return stringWriter.toString();
	}
}

src/main/java/com/openthinks/webscheduler/model/task/ExecutionResult.java
package com.openthinks.webscheduler.model.task;

import java.io.Serializable;
import java.util.Date;

import com.openthinks.webscheduler.help.StaticUtils;
import com.openthinks.webscheduler.model.Updateable;

public class ExecutionResult implements Serializable, Updateable<ExecutionResult> {

	private static final long serialVersionUID = 840962776805761590L;
	private Boolean success;
	private Date startTime;
	private Date endTime;
	protected String logContent;

	public ExecutionResult() {
		super();
	}

	public ExecutionResult start() {
		setStartTime(new Date());
		return this;
	}

	public ExecutionResult end() {
		setEndTime(new Date());
		return this;
	}

	public Boolean isSuccess() {
		return success;
	}

	public void setSuccess(boolean isSuccess) {
		this.success = isSuccess;
	}

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date executeTime) {
		this.startTime = executeTime;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getLogContent() {
		return logContent;
	}

	protected void setLogContent(String logContent) {
		this.logContent = logContent;
	}

	public void track(String log) {
		if (log != null) {
			if (this.logContent == null) {
				this.logContent = "";
			}
			this.logContent += log;
			this.logContent += "\r\n";
		}
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		if (this.isSuccess() != null) {
			sb.append("Execution: ");
			sb.append(this.success ? "Success" : "Failed");
			sb.append("\r\n");
		}
		if (this.getStartTime() != null) {
			sb.append("Start Time: ");
			sb.append(StaticUtils.formatDate(getStartTime()));
			sb.append("\r\n");
		}
		if (this.getEndTime() != null) {
			sb.append("End Time: ");
			sb.append(StaticUtils.formatDate(getEndTime()));
			sb.append("\r\n");
		}
		if (this.getLogContent() != null && this.getLogContent().length() > 0) {
			sb.append("Log Track: ");
			sb.append(this.getLogContent());
			sb.append("\r\n");
		}
		return sb.toString();
	}

	public void clear() {
		this.logContent = "";
		this.success = null;
		this.startTime = null;
		this.endTime = null;
	}

}

src/main/java/com/openthinks/webscheduler/model/task/ITaskTrigger.java
/**   
 *  Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
* @Title: ITaskTrigger.java 
* @Package com.openthinks.webscheduler.model.task 
* @Description: TODO
* @author dailey.yet@outlook.com  
* @date Aug 9, 2016
* @version V1.0   
*/
package com.openthinks.webscheduler.model.task;

import java.io.Serializable;

import org.quartz.Trigger;
import org.quartz.TriggerKey;

/**
 * @author dailey.yet@outlook.com
 *
 */
public interface ITaskTrigger extends Serializable {
	public SupportedTrigger getTriggerType();

	/**
	 * get the final job trigger
	 * @return Trigger
	 */
	public Trigger getTrigger();

	/**
	 * 
	 * @return TriggerKey
	 */
	public TriggerKey getTriggerKey();

	/**
	 * 
	 * @param triggerKey TriggerKey
	 */
	public void setTriggerKey(TriggerKey triggerKey);

}

src/main/java/com/openthinks/webscheduler/model/task/SupportedTrigger.java
/**   
 *  Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
* @Title: SupportedTrigger.java 
* @Package com.openthinks.webscheduler.task 
* @Description: TODO
* @author dailey.yet@outlook.com  
* @date Aug 9, 2016
* @version V1.0   
*/
package com.openthinks.webscheduler.model.task;

/**
 * @author dailey.yet@outlook.com
 *
 */
public enum SupportedTrigger {
	START_NOW("Start now", "simple1-trigger"), START_FIX_DATE("Start at one time",
			"simple2-trigger"), CRON("Cron expression", "cron-trigger");

	private String display, tag;

	private SupportedTrigger(String display, String tag) {
		this.display = display;
		this.tag = tag;
	}

	public String getDisplay() {
		return display;
	}

	public String getName() {
		return this.name();
	}

	public String getTag() {
		return tag;
	}

	@Override
	public String toString() {
		return getDisplay();
	}

}

src/main/java/com/openthinks/webscheduler/model/task/TaskAction.java
package com.openthinks.webscheduler.model.task;

/**
 * Task support action in page
 * @author dailey.yet@outlook.com
 *
 */
public enum TaskAction {
	Schedule, UnSchedule, Stop, Edit, Remove
}

src/main/java/com/openthinks/webscheduler/model/task/TaskState.java
package com.openthinks.webscheduler.model.task;

/**
 * Task support state 
 * @author dailey.yet@outlook.com
 *
 */
public enum TaskState {
	UN_SCHEDULE("Unschedule"), SCHEDULED("Scheduled"), RUNNING("Running"), COMPLETE("Completed"), INTERRUPT(
			"Interrupted"), INVALID("Invalid");

	private String key;
	private String display;

	private TaskState(String display) {
		this.key = this.toString();
		this.display = display;
	}

	public String getDisplay() {
		return display;
	}

	public String getKey() {
		return key;
	}
}

src/main/webapp/WEB-INF/jsp/task/edit.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="ew" uri="http://www.openthinks.com/easyweb"%>
<%@ taglib prefix="wsfn" uri="http://www.openthinks.com/webscheduler/fns"%>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="dailey.yet@outlook.com">
<title>Task - Edit</title>
<%@ include file="../template/head.style.jsp"%>
<link rel="stylesheet" href="${ew:pathS('/static/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css')}">
<link rel="stylesheet" href="${ew:pathS('/static/bootstrap-switch/css/bootstrap3/bootstrap-switch.min.css')}">
<link rel="stylesheet" href="${ew:pathS('/static/bootstrap-select/css/bootstrap-select.min.css')}">
<link rel="stylesheet" href="${ew:pathS('/static/CodeMirror/lib/codemirror.css')}">
<link rel="stylesheet" href="${ew:pathS('/static/css/task.css')}">
</head>
<body>
	<jsp:include page="../template/navbar.jsp" />
	<div class="container-fluid">
		<div class="row">
			<jsp:include page="../template/sidebar.jsp">
				<jsp:param name="active" value="tasks" />
			</jsp:include>
			<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
				<h1 class="page-header">Task <small>Edit</small></h1>
				<form action="${ew:path('/task/edit')}" method="post"
					class="form-horizontal">
					<div class="form-group">
						<label for="taskid" class="col-sm-2 control-label">Task
							ID</label>
						<div class="col-sm-10">
							<input type="hidden" class="form-control" id="taskid"
								name="taskid"  value="${pm.tm.taskId }">
							<p class="form-control-static">${pm.tm.taskId }</p>
						</div>
					</div>
					
					<div class="form-group">
						<label for="taskname" class="col-sm-2 control-label">Task
							name</label>
						<div class="col-sm-10">
							<input type="text" class="form-control" id="taskname"
								name="taskname" placeholder="task name" 
								value="${pm.tm.taskName }"
								required>
						</div>
					</div>

					<div class="form-group">
						<label for="taskname" class="col-sm-2 control-label">Task
							type</label>
						<div class="col-sm-10">
							<select id="tasktype" name="tasktype" class="form-control" required>

								<c:forEach var="task" items="${pm.supportTasks }" varStatus="status">
									<option <c:if test="${pm.tm.taskType==task.type.name }">selected</c:if> 
									data-required="${task.refDescriber.required }" data-ref="st_${status.index }" value="${task.type.name }" title="${task.describer.description }">${task.type.simpleName }</option>
								</c:forEach>
								<option value="" disabled="disabled">--------------------------</option>
								<c:forEach var="task" items="${pm.customTasks }" varStatus="status">
									<option <c:if test="${pm.tm.taskType==task.type.name }">selected</c:if>  
									data-required="${task.refDescriber.required }" data-ref="ct_${status.index }" value="${task.type.name }" title="${task.describer.description }">${task.type.simpleName }</option>
								</c:forEach>
							</select>
							<div class="hidden" id="tasktype-ref">
								<c:forEach var="task" items="${pm.supportTasks }" varStatus="status">
									<code id="st_${status.index }" >${task.refDescriber.description }</code>
								</c:forEach>
								<c:forEach var="task" items="${pm.customTasks }" varStatus="status">
									<code id="ct_${status.index }">${task.refDescriber.description }</code>
								</c:forEach>
							</div>
						</div>
					</div>
					
					<div class="form-group">
						<label for="tasktrigger" class="col-sm-2 control-label">Task trigger</label>
						<div class="col-sm-10">
							<select id="tasktrigger" name="tasktrigger" class="form-control" required>
								<c:forEach var="trigger" items="${pm.triggers }" varStatus="status">
									<option  <c:if test="${pm.tm.taskTrigger.triggerType == trigger }">selected</c:if> data-ref=".${trigger.tag}" value="${trigger.name }" title="${trigger.display }">${trigger.display }</option>
								</c:forEach>
							</select>
						</div>
					</div>
					<!-- trigger details for simple -->
					<div class="trigger-group simple1-trigger simple2-trigger" style="display: none">
						<div class="form-group" data-bind-target=".simple2-trigger">
							<label for="startdate" class="col-sm-2 control-label">Start date</label>
							<div class="col-sm-10">
								<div class="input-group">
									<input class="form-control form-datetime" size="16" type="datetime" name="startdate" id="startdate" value="${wsfn:getStartDate(pm.tm) }" data-date-format="yyyy-mm-dd hh:ii"  readonly>
									<span class="input-group-addon" role="datetime-addon" data-action="remove"><i class="fa fa-times" aria-hidden="true"></i></span>
									<span class="input-group-addon" role="datetime-addon" data-action="show"><i class="fa fa-calendar" aria-hidden="true"></i></span>
								</div>
							</div>
						</div>					
						<div class="form-group">
							<label for="repeatable" class="col-sm-2 control-label">Repeat options</label>
							<div class="col-sm-10">
								<input class="bootstrap-switch" data-ref=".repeat-options-group" data-label-text="Repeatable" type="checkbox" 
								name="repeatable" id="repeatable" <c:if test="${wsfn:isSimple4Repeatable(pm.tm) }">checked</c:if> >
								<!-- <input class="bootstrap-switch" data-label-text="Forever" type="checkbox" name="repeatforever" id="repeatforever"> -->
							</div>
						</div>
						<!-- repeat options -->
						<div class="repeat-options-group">
							<div class="form-group">
								<div class="col-sm-5 col-sm-offset-2">
									<div class="input-group">
										<input placeholder="Repeat interval" min="0" title="Repeat interval" class="form-control" type="number" name="repeatinterval" id="repeatinterval" value="${wsfn:getRepeatInterval(pm.tm) }">
										<span class="input-group-addon">Second</span>
									</div>
								</div>
								<div class="visible-xs-inline">
									<p></p>
								</div>
								<div class="col-sm-5">
									<!-- <input placeholder="Repeat count" min="0" title="Repeat count" class="" type="number" name="repeatcount" id="repeatcount"> -->
									<select name="repeatcount"
									title="Choose one of the following..."
									 class="selectpicker show-tick " id="repeatcount" data-width="auto" data-live-search="true" data-show-subtext="true">
										<option data-content="<span class='label label-warning'>Repeat forever</span>" 
										<c:if test="${wsfn:getRepeatCount(pm.tm)==2147483647 }">selected</c:if> value="2147483647">Repeat forever</option>
										<option data-divider="true"></option>
										<c:forEach var="i" begin="1" end="10">
											<option <c:if test="${wsfn:getRepeatCount(pm.tm)==i }">selected</c:if> value="${i}" >Repeat ${i} time</option>
										</c:forEach>
									</select>
								</div>
							</div>
							<div class="form-group">
								<div class="col-sm-10 col-sm-offset-2">
									<div class="input-group">
										<input class="form-control form-datetime" placeholder="End date" type="datetime" name="enddate" id="enddate" data-date-format="yyyy-mm-dd hh:ii" readonly value="${wsfn:getEndDate(pm.tm) }">
										<span class="input-group-addon" role="datetime-addon" data-action="remove"><i class="fa fa-times" aria-hidden="true"></i></span>
										<span class="input-group-addon" role="datetime-addon" data-action="show"><i class="fa fa-calendar" aria-hidden="true"></i></span>
									</div>
								</div>
							</div>	
						</div><!-- end of repeat options -->
						
					</div>
					
					<!-- trigger details for cron -->
					<div class="form-group trigger-group cron-trigger " style="display: none">
						<label for="cronexpr" class="col-sm-2 control-label">Cron expression</label>
						<div class="col-sm-10">
							<div class=" input-group">
								<input class="form-control" type="text" name="cronexpr" id="cronexpr" value="${wsfn:getCronExpr(pm.tm) }">
								<span class="input-group-addon" role="cron-addon" data-ref=".cron-trigger" data-action="check" title="Expression validation" data-link="${ew:path('/task/check/cron')}"><i class="fa fa-check" aria-hidden="true"></i></span>
								<span class="input-group-addon" role="cron-addon" data-action="help" title="Cron help" data-link="${ew:path('/help')}#trigger-cron"><i class="fa fa-question-circle" aria-hidden="true"></i></span>
							</div>
						</div>
					</div>					
					
					<div class="form-group">
							<label for="taskshared" class="col-sm-2 control-label">Shared</label>
							<div class="col-sm-10">
								<input class="bootstrap-switch"  data-label-text="Shared" type="checkbox" name="taskshared_switch" id="taskshared_switch">
								<input type="hidden" name="taskshared" id="taskshared" value="${pm.tm.shared }"/>
							</div>
					</div>
					
					<div class="form-group">
						<label for="taskname" class="col-sm-2 control-label">Task
							properties</label>
						<div class="col-sm-10">
							<div class="btn-toolbar" role="toolbar" id="taskref-toolbar" aria-label="Ref Toolbar">
							  <div class="btn-group" role="group" aria-label="">
							  	<button data-role="example" type="button" title="show example" class="btn btn-default"><i class="fa fa-lightbulb-o" aria-hidden="true"></i></button>
							  	<button data-role="copy" type="button" title="copy to clipboard" class="btn btn-default" data-clipboard-target="#taskref"><i class="fa fa-clipboard" aria-hidden="true"></i></button>
							  	<button data-role="clear" type="button" title="clear" class="btn btn-default"><i class="fa fa-eraser" aria-hidden="true"></i></button>
							  </div>
							</div>
							<textarea class="form-control"  id="taskref" name="taskref" rows="10">${pm.tm.taskRefContent}</textarea>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10 ">
							<button type="submit" class="btn btn-primary">Apply Changes</button>
							<a class="btn btn-default " href="${ew:path('/task/index')}" role="button">Cancel</a>
						</div>
					</div>

				</form>
			</div>
		</div>
	</div>

	<%@ include file="../template/body.script.jsp"%>
	<script type="text/javascript" src="${ew:pathS('/static/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js')}"></script>
	<script type="text/javascript" src="${ew:pathS('/static/bootstrap-select/js/bootstrap-select.min.js')}"></script>
	<script type="text/javascript" src="${ew:pathS('/static/bootstrap-switch/js/bootstrap-switch.min.js')}"></script>
	<script type="text/javascript" src="${ew:pathS('/static/CodeMirror/lib/codemirror.js')}"></script>
	<script type="text/javascript" src="${ew:pathS('/static/CodeMirror/mode/properties/properties.js')}"></script>
	<script type="text/javascript" src="${ew:pathS('/static/CodeMirror/mode/xml/xml.js')}"></script>
	<script type="text/javascript" src="${ew:pathS('/static/js/clipboard.js/clipboard.min.js')}"></script>
	<script type="text/javascript" src="${ew:pathS('/static/js/task.edit.js')}"></script>
</body>
</html>