src/main/java/com/openthinks/webscheduler/model/security/Role.java
/**   
 *  Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
* @Title: Role.java 
* @Package com.openthinks.webscheduler.model 
* @Description: TODO
* @author dailey.yet@outlook.com  
* @date Aug 23, 2016
* @version V1.0   
*/
package com.openthinks.webscheduler.model.security;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import com.openthinks.webscheduler.help.StaticDict;
import com.openthinks.webscheduler.model.Statable.DefaultStatable;

/**
 * Role definition
 * @author dailey.yet@outlook.com
 *
 */
@XmlRootElement(name = "role")
@XmlAccessorType(XmlAccessType.FIELD)
public class Role extends DefaultStatable implements Serializable {
	private static final long serialVersionUID = -7271233095825354386L;
	@XmlAttribute
	protected String id;
	@XmlElement(name = "role-name")
	protected String name;
	@XmlElement(name = "role-desc")
	protected String desc;
	@XmlElement(name = "role-maps")
	private RoleMaps roleMaps;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		notifyChanged(this.id, id);
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		notifyChanged(this.name, name);
		this.name = name;
	}

	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		notifyChanged(this.desc, desc);
		this.desc = desc;
	}

	public RoleMaps getRoleMaps() {
		if (roleMaps == null) {
			this.roleMaps = new RoleMaps();
		}
		return roleMaps;
	}

	public String getJoinedRoleMaps() {
		String joinedMaps = getRoleMaps().getRoleMaps().stream().map((roleMap) -> {
			Set<String> joinedSet = new HashSet<>();
			if (roleMap.getInclude() != null && roleMap.getInclude().trim().length() > 0) {
				joinedSet.add(roleMap.getInclude());
			}
			if (roleMap.getPath() != null && roleMap.getPath().trim().length() > 0) {
				joinedSet.add(roleMap.getPath());
			}
			return joinedSet.stream().collect(Collectors.joining(StaticDict.PAGE_PARAM_LIST_JOIN));
		}).collect(Collectors.joining(StaticDict.PAGE_PARAM_LIST_JOIN));
		return joinedMaps;
	}

	public void setRoleMaps(RoleMaps roleMaps) {
		notifyChanged(this.roleMaps, roleMaps);
		this.roleMaps = roleMaps;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Role other = (Role) obj;
		if (id != null && id.equals(other.id))
			return true;
		if (name != null && name.equals(other.name))
			return true;
		return false;
	}

}

src/main/java/com/openthinks/webscheduler/controller/SettingController.java
/**   
 *  Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
* @Title: SettingController.java 
* @Package com.openthinks.webscheduler.controller 
* @Description: TODO
* @author dailey.yet@outlook.com  
* @date Aug 24, 2016
* @version V1.0   
*/
package com.openthinks.webscheduler.controller;

import java.io.IOException;
import java.util.Collection;
import java.util.List;
import java.util.Set;

import org.apache.commons.codec.digest.DigestUtils;
import org.quartz.SchedulerException;

import com.openthinks.easyweb.WebStatic;
import com.openthinks.easyweb.WebUtils;
import com.openthinks.easyweb.annotation.AutoComponent;
import com.openthinks.easyweb.annotation.Controller;
import com.openthinks.easyweb.annotation.Jsonp;
import com.openthinks.easyweb.annotation.Mapping;
import com.openthinks.easyweb.annotation.ResponseReturn;
import com.openthinks.easyweb.annotation.ResponseReturn.ResponseReturnType;
import com.openthinks.easyweb.context.WebContexts;
import com.openthinks.easyweb.context.handler.WebAttributers;
import com.openthinks.easyweb.context.handler.WebAttributers.WebScope;
import com.openthinks.easyweb.utils.json.OperationJson;
import com.openthinks.libs.utilities.Checker;
import com.openthinks.libs.utilities.logger.ProcessLogger;
import com.openthinks.libs.utilities.logger.ProcessLogger.PLLevel;
import com.openthinks.webscheduler.help.PageMap;
import com.openthinks.webscheduler.help.StaticDict;
import com.openthinks.webscheduler.help.StaticUtils;
import com.openthinks.webscheduler.help.confs.RootConfig;
import com.openthinks.webscheduler.model.Statable;
import com.openthinks.webscheduler.model.security.Role;
import com.openthinks.webscheduler.model.security.RoleMaps;
import com.openthinks.webscheduler.model.security.Roles;
import com.openthinks.webscheduler.model.security.User;
import com.openthinks.webscheduler.model.security.Users;
import com.openthinks.webscheduler.model.task.ITaskRef;
import com.openthinks.webscheduler.service.SchedulerService;
import com.openthinks.webscheduler.service.WebSecurityService;
import com.openthinks.webscheduler.task.ITaskDefinition;
import com.openthinks.webscheduler.task.TaskRefProtected;
import com.openthinks.webscheduler.task.TaskTypes;

/**
 * @author dailey.yet@outlook.com
 *
 */
@Controller("/setting")
public class SettingController {
	@AutoComponent
	WebSecurityService securityService;
	@AutoComponent
	SchedulerService schedulerService;

	@AutoComponent
	RootConfig rootConfig;

	@Mapping("/index")
	public String index() {
		return "WEB-INF/jsp/setting/index.jsp";
	}

	@Mapping("/role")
	public String role(WebAttributers was) {
		Roles rolesObj = securityService.getRoles();
		Set<Role> roles = rolesObj.getRoles();
		was.storeRequest(StaticDict.PAGE_ATTRIBUTE_ROLE_LIST, roles);
		was.storeRequest(StaticDict.PAGE_ATTRIBUTE_IS_IN_SYNC, rolesObj.isInSync());
		return "WEB-INF/jsp/setting/role/index.jsp";
	}

	@Mapping("/role/to/add")
	public String toAddRole(WebAttributers was) {
		was.storeRequest(StaticDict.PAGE_ATTRIBUTE_WEB_CONTROLLER_LIST,
				WebContexts.get().getWebContainer().getWebControllers());
		was.storeRequest(StaticDict.PAGE_ATTRIBUTE_ROLE_LIST, securityService.getRoles().getRoles());
		return "WEB-INF/jsp/setting/role/add.jsp";
	}

	@Mapping("/role/add")
	public String addRole(WebAttributers was) {
		boolean isSuccess = false;
		PageMap pm = newPageMap();
		String roleName = was.get(StaticDict.PAGE_PARAM_ROLE_NAME);
		String roleDesc = was.get(StaticDict.PAGE_PARAM_ROLE_DESC);
		String rolemaps = was.get(StaticDict.PAGE_PARAM_ROLE_MAPS);
		try {
			Checker.require(roleName).notEmpty("Role name can not be empty.");
			Checker.require(rolemaps).notEmpty("Role maps can not be empty.");
		} catch (Exception e) {
			was.addError(StaticDict.PAGE_ATTRIBUTE_ERROR_1, e.getMessage(), WebScope.REQUEST);
			return StaticUtils.errorPage(was, pm);
		}
		Role role = new Role();
		role.setId(StaticUtils.UUID());
		role.setName(roleName);
		role.setRoleMaps(RoleMaps.valueOf(rolemaps));
		role.setDesc(roleDesc);
		isSuccess = securityService.getRoles().add(role);
		if (!isSuccess) {
			was.addError(StaticDict.PAGE_ATTRIBUTE_ERROR_1,
					"Couldn't add this role, maybe this role name has already been used.", WebScope.REQUEST);
			return StaticUtils.errorPage(was, pm);
		}
		pm.push("title", "Setting - Adding role").push("redirectUrl", WebUtils.path("/setting/role"));
		return StaticUtils.intermediatePage(was, pm);
	}

	@Mapping("/role/to/edit")
	public String toEditRole(WebAttributers was) {
		String roleId = was.get(StaticDict.PAGE_PARAM_ROLE_ID);
		Role role = securityService.getRoles().findById(roleId);
		if (role == null) {
			was.addError(StaticDict.PAGE_ATTRIBUTE_ERROR_1, "Couldn't found this role, please check and do it again.",
					WebScope.REQUEST);
			return StaticUtils.errorPage(was, this.newPageMap());
		}
		was.storeRequest(StaticDict.PAGE_ATTRIBUTE_ROLE, role);
		Set<Role> otherRoles = securityService.getRoles().findByPredicate((roleTest) -> {
			return !role.equals(roleTest);
		});
		was.storeRequest(StaticDict.PAGE_ATTRIBUTE_ROLE_LIST, otherRoles);
		was.storeRequest(StaticDict.PAGE_ATTRIBUTE_WEB_CONTROLLER_LIST,
				WebContexts.get().getWebContainer().getWebControllers());
		return "WEB-INF/jsp/setting/role/edit.jsp";
	}

	@Mapping("/role/edit")
	public String editRole(WebAttributers was) {
		boolean isSuccess = false;
		PageMap pm = newPageMap();
		String roleId = was.get(StaticDict.PAGE_PARAM_ROLE_ID);
		Role role = securityService.getRoles().findById(roleId);
		if (role == null) {
			was.addError(StaticDict.PAGE_ATTRIBUTE_ERROR_1, "Couldn't save this role, because not find this role.",
					WebScope.REQUEST);
			return StaticUtils.errorPage(was, pm);
		}
		String roleName = was.get(StaticDict.PAGE_PARAM_ROLE_NAME);
		String roleDesc = was.get(StaticDict.PAGE_PARAM_ROLE_DESC);
		String rolemaps = was.get(StaticDict.PAGE_PARAM_ROLE_MAPS);
		try {
			Checker.require(roleName).notEmpty("Role name can not be empty.");
			Checker.require(rolemaps).notEmpty("Role maps can not be empty.");
		} catch (Exception e) {
			was.addError(StaticDict.PAGE_ATTRIBUTE_ERROR_1, e.getMessage(), WebScope.REQUEST);
			return StaticUtils.errorPage(was, pm);
		}
		if (!roleName.equals(role.getName())) {
			Role duplicateRole = securityService.getRoles().findByName(roleName);
			if (duplicateRole != null) {
				was.addError(StaticDict.PAGE_ATTRIBUTE_ERROR_1,
						"Couldn't save this role, maybe this name has already been used.", WebScope.REQUEST);
				return StaticUtils.errorPage(was, pm);
			}
		}
		role.setName(roleName);
		role.setRoleMaps(RoleMaps.valueOf(rolemaps));
		role.setDesc(roleDesc);
		isSuccess = true;
		if (!isSuccess) {
			was.addError(StaticDict.PAGE_ATTRIBUTE_ERROR_1,
					"Couldn't save this role, maybe this name has already been used.", WebScope.REQUEST);
			return StaticUtils.errorPage(was, pm);
		}
		pm.push("title", "Setting - Editing role").push("redirectUrl", WebUtils.path("/setting/role"));
		return StaticUtils.intermediatePage(was, pm);
	}

	@Mapping("/role/sync")
	public String syncRole(WebAttributers was) {
		PageMap pm = newPageMap();
		try {
			securityService.saveToDisk();
		} catch (Exception e) {
			was.addError(StaticDict.PAGE_ATTRIBUTE_ERROR_1, "Couldn't sync roles, root cause:" + e.getMessage(),
					WebScope.REQUEST);
			return StaticUtils.errorPage(was, pm);
		}
		pm.push("title", "Setting - Syncing Roles").push("redirectUrl", WebUtils.path("/setting/role"));
		return StaticUtils.intermediatePage(was, pm);
	}

	@Mapping("/user")
	public String user(WebAttributers was) {
		Users usersObj = securityService.getUsers();
		Set<User> users = usersObj.getUsers();
		was.storeRequest(StaticDict.PAGE_ATTRIBUTE_USER_LIST, users);
		was.storeRequest(StaticDict.PAGE_ATTRIBUTE_IS_IN_SYNC, usersObj.isInSync());
		return "WEB-INF/jsp/setting/user/index.jsp";
	}

	@Mapping("/user/to/add")
	public String toAddUser(WebAttributers was) {
		Set<Role> roles = securityService.getRoles().getRoles();
		was.storeRequest(StaticDict.PAGE_ATTRIBUTE_ROLE_LIST, roles);
		return "WEB-INF/jsp/setting/user/add.jsp";
	}

	@Mapping("/user/add")
	public String addUser(WebAttributers was) {
		boolean isSuccess = false;
		PageMap pm = newPageMap();
		String userName = was.get(StaticDict.PAGE_PARAM_USER_NAME);
		String userEmail = was.get(StaticDict.PAGE_PARAM_USER_EMAIL);
		String userPass = was.get(StaticDict.PAGE_PARAM_USER_PASS);
		String userRoles = was.get(StaticDict.PAGE_PARAM_USER_ROLES);
		try {
			Checker.require(userName).notEmpty("User name can not be empty.");
			Checker.require(userEmail).notEmpty("User email can not be empty.");
			Checker.require(userPass).notEmpty("User password can not be empty.");
			Checker.require(userRoles).notEmpty("User roles can not be empty.");
		} catch (Exception e) {
			was.addError(StaticDict.PAGE_ATTRIBUTE_ERROR_1, e.getMessage(), WebScope.REQUEST);
			return StaticUtils.errorPage(was, pm);
		}
		User user = new User();
		user.setId(StaticUtils.UUID());

src/main/webapp/WEB-INF/jsp/setting/role/add.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib prefix="ew" uri="http://www.openthinks.com/easyweb"%>
<%@ taglib prefix="wsfn"
	uri="http://www.openthinks.com/webscheduler/fns"%>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="dailey.yet@outlook.com">
<title>Setting - Role</title>
<%@ include file="../../template/head.style.jsp"%>
<link rel="stylesheet" href="${ew:pathS('/static/bootstrap-select/css/bootstrap-select.min.css')}">
</head>
<body>
	<jsp:include page="../../template/navbar.jsp" />
	<div class="container-fluid">
		<div class="row">
			<jsp:include page="../../template/sidebar.jsp">
				<jsp:param name="active" value="settings" />
			</jsp:include>
			<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
				<h1 class="page-header">
					Setting <small>Roles</small>
				</h1>
				<form action="${ew:path('/setting/role/add')}" method="post"
					class="form-horizontal">
					<div class="form-group">
						<label for="rolename" class="col-sm-2 control-label">Role
							name</label>
						<div class="col-sm-10">
							<input type="text" class="form-control" id="rolename"
								name="rolename" placeholder="role name" required>
						</div>
					</div>
					<div class="form-group">
						<label for="rolemaps" class="col-sm-2 control-label">Role maps</label>
						<div class="col-sm-10">
							<input type="hidden" name="rolemaps" id="rolemaps"/>
							<select name="rolemaps-sel-path"  title="Choose some of the following paths..."
								class="selectpicker show-tick " id="rolemaps-sel-path" data-width="auto"
								data-live-search="true" data-show-subtext="true" multiple data-selected-text-format="count > 3">
								<c:forEach var="webCtr" items="${webControllers }">
									<optgroup label="<code>${webCtr.relativePath }</code><small>${webCtr.name }</small>">
										<c:forEach var="webMethod" items="${webCtr.webMethods }">
											<option value="${webMethod.relativePath2 }" data-content="<kbd>${webMethod.relativePath }</kbd><small>${webMethod.name }</small>"></option>
										</c:forEach>
									</optgroup>
								</c:forEach>
							</select>
							<p class="visible-xs-block visible-sm-block"></p>
							<span> <code >&nbsp;+&nbsp;</code> </span>
							<select name="rolemaps-sel-include" id="rolemaps-sel-include"  data-width="auto" class="selectpicker show-tick"
							data-show-subtext="true" multiple data-selected-text-format="count > 3"
							title="Include some of the following roles...">
								<c:forEach var="role" items="${roles }">
									<option value="${role.id }">${role.name }</option>
								</c:forEach>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="roledesc" class="col-sm-2 control-label">Role
							description</label>
						<div class="col-sm-10">
							<textarea class="form-control" id="roledesc" name="roledesc"></textarea>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10 ">
							<button type="submit" class="btn btn-primary">Apply
								Changes</button>
							<a class="btn btn-default " href="${ew:path('/setting/role')}"
								role="button">Cancel</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	<%@ include file="../../template/body.script.jsp"%>
	<script type="text/javascript"
		src="${ew:pathS('/static/bootstrap-select/js/bootstrap-select.min.js')}"></script>
	<script type="text/javascript"
		src="${ew:pathS('/static/js/setting.role.add.js')}"></script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/setting/role/edit.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib prefix="ew" uri="http://www.openthinks.com/easyweb"%>
<%@ taglib prefix="wsfn"
	uri="http://www.openthinks.com/webscheduler/fns"%>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="dailey.yet@outlook.com">
<title>Setting - Role</title>
<%@ include file="../../template/head.style.jsp"%>
<link rel="stylesheet" href="${ew:pathS('/static/bootstrap-select/css/bootstrap-select.min.css')}">
</head>
<body>
	<jsp:include page="../../template/navbar.jsp" />
	<div class="container-fluid">
		<div class="row">
			<jsp:include page="../../template/sidebar.jsp">
				<jsp:param name="active" value="settings" />
			</jsp:include>
			<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
				<h1 class="page-header">
					Setting <small>Roles</small>
				</h1>
				<form action="${ew:path('/setting/role/edit')}" method="post"
					class="form-horizontal">
					<div class="form-group">
						<label for="rolename" class="col-sm-2 control-label">Role
							name</label>
						<div class="col-sm-10">
							<input type="hidden" class="form-control" id="roleid"
								name="roleid" value="${role.id }">
							<input type="text" class="form-control" id="rolename"
								name="rolename" placeholder="role name" value="${role.name }" required>
						</div>
					</div>
					<div class="form-group">
						<label for="rolemaps" class="col-sm-2 control-label">Role maps</label>
						<div class="col-sm-10">
							<input type="hidden" name="rolemaps" id="rolemaps" value="${role.joinedRoleMaps }"/>
							<select name="rolemaps-sel-path" required title="Choose some of the following paths..."
								class="selectpicker show-tick " id="rolemaps-sel-path" data-width="auto"
								data-live-search="true" data-show-subtext="true" multiple data-selected-text-format="count > 3">
								<c:forEach var="webCtr" items="${webControllers }">
									<optgroup label="<code>${webCtr.relativePath }</code><small>${webCtr.name }</small>">
										<c:forEach var="webMethod" items="${webCtr.webMethods }">
											<option value="${webMethod.relativePath2 }" 
											data-content="<kbd>${webMethod.relativePath }</kbd><small>${webMethod.name }</small>" 
											<c:if test="${fn:contains(role.joinedRoleMaps , webMethod.relativePath2)}">selected</c:if> >
											</option>
										</c:forEach>
									</optgroup>
								</c:forEach>
							</select>
							<p class="visible-xs-block visible-sm-block"></p>
							<span> <code >&nbsp;+&nbsp;</code> </span>
							<select name="rolemaps-sel-include" id="rolemaps-sel-include"  data-width="auto" class="selectpicker show-tick"
							data-show-subtext="true" multiple data-selected-text-format="count > 3"
							title="Include some of the following roles...">
								<c:forEach var="othrole" items="${roles }">
									<option value="${othrole.id }" 
									<c:if test="${fn:contains(role.joinedRoleMaps , othrole.id)}">selected</c:if> >
										${othrole.name }
									</option>
								</c:forEach>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="roledesc" class="col-sm-2 control-label">Role
							description</label>
						<div class="col-sm-10">
							<textarea class="form-control" id="roledesc" name="roledesc">${role.desc }</textarea>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10 ">
							<button type="submit" class="btn btn-primary">Apply
								Changes</button>
							<a class="btn btn-default " href="${ew:path('/setting/role')}"
								role="button">Cancel</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	<%@ include file="../../template/body.script.jsp"%>
	<script type="text/javascript"
		src="${ew:pathS('/static/bootstrap-select/js/bootstrap-select.min.js')}"></script>
	<script type="text/javascript"
		src="${ew:pathS('/static/js/setting.role.edit.js')}"></script>
</body>
</html>